<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EmailTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'id' => Str::uuid(),
                'name' => 'Confirmation d\'inscription',
                'code' => 'welcome_player',
                'type' => 'notification',
                'target_types' => 'JOUEURS',
                'subject' => 'Bienvenue sur ÉcoloQuiz ! 🌱',
                'sender_name' => 'ÉcoloQuiz',
                'sender_email' => 'contact@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => null,
                'body_html' => '<h1>Bienvenue {{player_name}} !</h1><p>Votre compte a été créé avec succès.</p>',
                'body_text' => 'Bienvenue {{player_name}} ! Votre compte a été créé avec succès.',
                'variables_schema' => json_encode(['player_name', 'player_email']),
                'is_active' => true,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Invitation parrainage',
                'code' => 'referral_invitation',
                'type' => 'info',
                'target_types' => 'TOUS',
                'subject' => '{{sender_name}} vous invite à rejoindre ÉcoloQuiz',
                'sender_name' => 'ÉcoloQuiz',
                'sender_email' => 'invitations@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => null,
                'body_html' => '<p>{{sender_name}} vous invite à rejoindre ÉcoloQuiz.</p><p><a href="{{referral_link}}">S\'inscrire</a></p>',
                'body_text' => '{{sender_name}} vous invite à rejoindre ÉcoloQuiz. Inscrivez-vous : {{referral_link}}',
                'variables_schema' => json_encode(['sender_name', 'referral_link', 'recipient_email']),
                'is_active' => true,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Notification cadeau disponible',
                'code' => 'gift_available',
                'type' => 'alerte',
                'target_types' => 'JOUEURS',
                'subject' => '🎁 Un cadeau vous attend !',
                'sender_name' => 'ÉcoloQuiz',
                'sender_email' => 'cadeaux@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => null,
                'body_html' => '<h2>Félicitations {{player_name}} !</h2><p>Vous avez gagné : {{gift_name}}</p>',
                'body_text' => 'Félicitations {{player_name}} ! Vous avez gagné : {{gift_name}}',
                'variables_schema' => json_encode(['player_name', 'gift_name', 'gift_code']),
                'is_active' => true,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Réinitialisation mot de passe',
                'code' => 'password_reset',
                'type' => 'notification',
                'target_types' => 'TOUS',
                'subject' => 'Réinitialisez votre mot de passe',
                'sender_name' => 'ÉcoloQuiz',
                'sender_email' => 'noreply@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => null,
                'body_html' => '<p>Cliquez sur ce lien pour réinitialiser votre mot de passe : <a href="{{reset_link}}">Réinitialiser</a></p>',
                'body_text' => 'Cliquez sur ce lien pour réinitialiser votre mot de passe : {{reset_link}}',
                'variables_schema' => json_encode(['user_email', 'reset_link', 'expiration_time']),
                'is_active' => true,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Newsletter mensuelle',
                'code' => 'monthly_newsletter',
                'type' => 'info',
                'target_types' => 'TOUS',
                'subject' => '📰 Votre résumé ÉcoloQuiz du mois',
                'sender_name' => 'L\'équipe ÉcoloQuiz',
                'sender_email' => 'newsletter@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => null,
                'body_html' => '<h1>Votre mois en chiffres</h1><p>Vous avez joué {{quiz_count}} quiz ce mois-ci.</p>',
                'body_text' => 'Votre mois en chiffres : Vous avez joué {{quiz_count}} quiz ce mois-ci.',
                'variables_schema' => json_encode(['user_name', 'quiz_count', 'points_earned', 'ranking']),
                'is_active' => false,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Rappel quiz en cours',
                'code' => 'quiz_reminder',
                'type' => 'notification',
                'target_types' => 'JOUEURS',
                'subject' => '⏰ N\'oubliez pas de terminer votre quiz !',
                'sender_name' => 'ÉcoloQuiz',
                'sender_email' => 'notifications@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => null,
                'body_html' => '<p>Bonjour {{player_name}},</p><p>Vous avez un quiz en cours : {{quiz_title}}</p>',
                'body_text' => 'Bonjour {{player_name}}, vous avez un quiz en cours : {{quiz_title}}',
                'variables_schema' => json_encode(['player_name', 'quiz_title', 'quiz_link']),
                'is_active' => true,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Nouveau quiz disponible',
                'code' => 'new_quiz_available',
                'type' => 'info',
                'target_types' => 'JOUEURS',
                'subject' => '✨ Nouveau quiz : {{quiz_title}}',
                'sender_name' => 'ÉcoloQuiz',
                'sender_email' => 'nouveautes@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => null,
                'body_html' => '<h2>Nouveau quiz disponible !</h2><p>Découvrez {{quiz_title}} dans la catégorie {{theme_name}}</p>',
                'body_text' => 'Nouveau quiz disponible ! Découvrez {{quiz_title}} dans la catégorie {{theme_name}}',
                'variables_schema' => json_encode(['quiz_title', 'theme_name', 'quiz_link']),
                'is_active' => true,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Bienvenue entreprise partenaire',
                'code' => 'welcome_company',
                'type' => 'notification',
                'target_types' => 'ENTREPRISES',
                'subject' => 'Bienvenue sur ÉcoloQuiz Business',
                'sender_name' => 'ÉcoloQuiz Business',
                'sender_email' => 'partenaires@ecoloquiz.fr',
                'to' => null,
                'cc' => null,
                'bcc' => 'admin@ecoloquiz.fr',
                'body_html' => '<h1>Bienvenue {{company_name}} !</h1><p>Votre espace partenaire est prêt.</p>',
                'body_text' => 'Bienvenue {{company_name}} ! Votre espace partenaire est prêt.',
                'variables_schema' => json_encode(['company_name', 'contact_name', 'dashboard_link']),
                'is_active' => true,
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('email_templates')->insert($templates);
    }
}
